--
-- PostgreSQL database dump
--

\restrict 5jFZxnyv7Zg0kyQkGiutpL3rvWiTmDP3fXnPIY1pSMmht4FZehS2Vc5NreivRy8

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: match_attendances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.match_attendances (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    overall smallint NOT NULL,
    id uuid NOT NULL,
    display_name character varying(120) NOT NULL,
    is_guest boolean NOT NULL,
    attendance_status character varying(16) NOT NULL,
    assigned_team_number smallint,
    assigned_team_name character varying(32) NOT NULL,
    confirmed_at timestamp with time zone,
    notes text NOT NULL,
    invited_by_id uuid,
    match_id uuid NOT NULL,
    player_id uuid,
    guest_fee_amount numeric(8,2) NOT NULL,
    guest_fee_status character varying(16) NOT NULL,
    guest_fee_paid_at timestamp with time zone,
    CONSTRAINT match_attendances_assigned_team_number_check CHECK ((assigned_team_number >= 0)),
    CONSTRAINT match_attendances_overall_check CHECK ((overall >= 0))
);


--
-- Name: match_player_ratings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.match_player_ratings (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    score smallint NOT NULL,
    match_id uuid NOT NULL,
    rated_attendance_id uuid NOT NULL,
    rated_player_id uuid NOT NULL,
    rater_id uuid,
    rater_user_id uuid,
    CONSTRAINT match_player_rating_score_1_10 CHECK (((score >= 1) AND (score <= 10))),
    CONSTRAINT match_player_ratings_score_check CHECK ((score >= 0))
);


--
-- Name: matches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.matches (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    scheduled_at timestamp with time zone NOT NULL,
    location character varying(120) NOT NULL,
    status character varying(16) NOT NULL,
    expected_team_count smallint NOT NULL,
    attendance_locked_at timestamp with time zone,
    teams_generated_at timestamp with time zone,
    notes text NOT NULL,
    created_by_id uuid,
    result_recorded_at timestamp with time zone,
    result_summary text NOT NULL,
    archived_at timestamp with time zone,
    ratings_finalized_at timestamp with time zone,
    CONSTRAINT matches_expected_team_count_check CHECK ((expected_team_count >= 0))
);


--
-- Name: players; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.players (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    overall smallint NOT NULL,
    id uuid NOT NULL,
    full_name character varying(120) NOT NULL,
    nickname character varying(60) NOT NULL,
    player_type character varying(16) NOT NULL,
    preferred_position character varying(16) NOT NULL,
    email character varying(254) NOT NULL,
    phone_number character varying(32) NOT NULL,
    shirt_number smallint,
    monthly_fee_amount numeric(8,2) NOT NULL,
    joined_on date,
    is_active boolean NOT NULL,
    notes text NOT NULL,
    CONSTRAINT players_overall_check CHECK ((overall >= 0)),
    CONSTRAINT players_shirt_number_check CHECK ((shirt_number >= 0))
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    direction character varying(8) NOT NULL,
    category character varying(24) NOT NULL,
    status character varying(16) NOT NULL,
    amount numeric(10,2) NOT NULL,
    description character varying(255) NOT NULL,
    occurred_on date NOT NULL,
    reference_month date,
    external_reference character varying(120) NOT NULL,
    notes text NOT NULL,
    match_id uuid,
    recorded_by_id uuid,
    related_player_id uuid
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    role character varying(16) NOT NULL,
    display_name character varying(120) NOT NULL,
    must_change_password boolean NOT NULL,
    linked_player_id uuid,
    phone_number character varying(32) NOT NULL
);


--
-- Name: users_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_groups (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user_permissions (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Token	6	add_token
22	Can change Token	6	change_token
23	Can delete Token	6	delete_token
24	Can view Token	6	view_token
25	Can add Token	7	add_tokenproxy
26	Can change Token	7	change_tokenproxy
27	Can delete Token	7	delete_tokenproxy
28	Can view Token	7	view_tokenproxy
29	Can add player	8	add_player
30	Can change player	8	change_player
31	Can delete player	8	delete_player
32	Can view player	8	view_player
33	Can add user	9	add_user
34	Can change user	9	change_user
35	Can delete user	9	delete_user
36	Can view user	9	view_user
37	Can add match	10	add_match
38	Can change match	10	change_match
39	Can delete match	10	delete_match
40	Can view match	10	view_match
41	Can add transaction	11	add_transaction
42	Can change transaction	11	change_transaction
43	Can delete transaction	11	delete_transaction
44	Can view transaction	11	view_transaction
45	Can add match attendance	12	add_matchattendance
46	Can change match attendance	12	change_matchattendance
47	Can delete match attendance	12	delete_matchattendance
48	Can view match attendance	12	view_matchattendance
49	Can add match player rating	13	add_matchplayerrating
50	Can change match player rating	13	change_matchplayerrating
51	Can delete match player rating	13	delete_matchplayerrating
52	Can view match player rating	13	view_matchplayerrating
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
48bba56fc689fdad402062e37126d0b5b8437e9a	2026-05-21 23:04:56.503676+00	e0c910c5-a6c6-4ff0-a962-1c03209bb446
76d571d00660e427b2051a4e5dcb337334489cbc	2026-06-02 21:11:14.545546+00	bbd1d373-10e2-454c-bfac-4ecaebb5d40c
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	authtoken	token
7	authtoken	tokenproxy
8	core	player
9	core	user
10	core	match
11	core	transaction
12	core	matchattendance
13	core	matchplayerrating
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-14 14:05:45.787398+00
2	contenttypes	0002_remove_content_type_name	2026-04-14 14:05:45.798881+00
3	auth	0001_initial	2026-04-14 14:05:45.900001+00
4	auth	0002_alter_permission_name_max_length	2026-04-14 14:05:45.909213+00
5	auth	0003_alter_user_email_max_length	2026-04-14 14:05:45.917807+00
6	auth	0004_alter_user_username_opts	2026-04-14 14:05:45.926169+00
7	auth	0005_alter_user_last_login_null	2026-04-14 14:05:45.934379+00
8	auth	0006_require_contenttypes_0002	2026-04-14 14:05:45.940164+00
9	auth	0007_alter_validators_add_error_messages	2026-04-14 14:05:45.94793+00
10	auth	0008_alter_user_username_max_length	2026-04-14 14:05:45.955948+00
11	auth	0009_alter_user_last_name_max_length	2026-04-14 14:05:45.964204+00
12	auth	0010_alter_group_name_max_length	2026-04-14 14:05:45.976233+00
13	auth	0011_update_proxy_permissions	2026-04-14 14:05:45.986027+00
14	auth	0012_alter_user_first_name_max_length	2026-04-14 14:05:45.994032+00
15	core	0001_initial	2026-04-14 14:05:46.494388+00
16	admin	0001_initial	2026-04-14 14:05:46.55289+00
17	admin	0002_logentry_remove_auto_add	2026-04-14 14:05:46.567139+00
18	admin	0003_logentry_add_action_flag_choices	2026-04-14 14:05:46.580689+00
19	authtoken	0001_initial	2026-04-14 14:05:46.624841+00
20	authtoken	0002_auto_20160226_1747	2026-04-14 14:05:46.661533+00
21	authtoken	0003_tokenproxy	2026-04-14 14:05:46.669189+00
22	authtoken	0004_alter_tokenproxy_options	2026-04-14 14:05:46.677875+00
23	core	0002_match_result_fields	2026-04-14 14:05:46.709379+00
24	core	0003_rename_matches_scheduled_at_a21724_idx_matches_schedul_821885_idx_and_more	2026-04-14 14:05:46.820416+00
25	sessions	0001_initial	2026-04-14 14:05:46.864246+00
26	core	0004_remove_matchattendance_attack_and_more	2026-05-21 19:39:59.604412+00
27	core	0005_matchplayerrating_and_more	2026-05-21 21:03:33.743812+00
28	core	0006_user_phone_number_user_users_phone_n_a3b1c5_idx	2026-05-21 22:30:12.229462+00
29	core	0007_matchplayerrating_rater_user	2026-05-21 23:01:33.335012+00
30	core	0008_match_rating_window	2026-05-26 20:50:49.347322+00
31	core	0009_guest_fee_tracking	2026-05-26 22:17:25.900295+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: match_attendances; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.match_attendances (created_at, updated_at, overall, id, display_name, is_guest, attendance_status, assigned_team_number, assigned_team_name, confirmed_at, notes, invited_by_id, match_id, player_id, guest_fee_amount, guest_fee_status, guest_fee_paid_at) FROM stdin;
2026-05-26 22:23:46.281263+00	2026-05-26 22:23:46.281274+00	70	39a0dc62-693e-4151-9332-f5d04beb5b1e	Messias	f	CONFIRMED	1	Time 1	2026-05-26 22:23:46.280963+00		\N	c7479212-3f63-4751-a39d-ca412b4194d0	be21556d-bb4b-4543-81fe-6e5ad485e640	0.00	WAIVED	\N
2026-05-26 22:23:47.491185+00	2026-05-26 22:23:47.491204+00	70	34e7d8bd-c8e0-454a-ab17-e2f67e12e7df	Moises	f	CONFIRMED	1	Time 1	2026-05-26 22:23:47.490726+00		\N	c7479212-3f63-4751-a39d-ca412b4194d0	8ae512a8-21f8-4552-acb0-31935de4d194	0.00	WAIVED	\N
2026-05-26 22:23:50.865177+00	2026-05-26 22:23:50.865189+00	65	fa978f61-3e01-4e11-b452-17be12c575a0	Thiago Mozzer	f	CONFIRMED	1	Time 1	2026-05-26 22:23:50.864869+00		\N	c7479212-3f63-4751-a39d-ca412b4194d0	651e725a-f346-4e13-9f4a-94074959a035	0.00	WAIVED	\N
2026-05-26 22:23:35.020011+00	2026-05-26 22:23:35.020021+00	45	baaa7999-4aa0-4c69-8584-46cdd45165e9	Baiano	f	CONFIRMED	1	Time 1	2026-05-26 22:23:35.019724+00		\N	c7479212-3f63-4751-a39d-ca412b4194d0	5f39e8f8-8b69-470c-b557-64ec3ca76793	0.00	WAIVED	\N
2026-05-26 22:23:36.117935+00	2026-05-26 22:23:36.117946+00	85	ebfc0f65-6eca-4e48-a3ec-dcf077b0c975	Daniel Gusmao	f	CONFIRMED	2	Time 2	2026-05-26 22:23:36.117642+00		\N	c7479212-3f63-4751-a39d-ca412b4194d0	7f11d3fd-7dc6-40ff-8362-8408d600cae7	0.00	WAIVED	\N
2026-05-26 22:23:42.070623+00	2026-05-26 22:23:42.070633+00	70	ace4dabb-bb2f-40e1-ac87-3b6fac2535e9	Joao Pedro Marinho	f	CONFIRMED	2	Time 2	2026-05-26 22:23:42.070334+00		\N	c7479212-3f63-4751-a39d-ca412b4194d0	7726eb14-57d9-4835-bdbc-63b8605e4d5b	0.00	WAIVED	\N
2026-05-26 22:24:46.777243+00	2026-05-26 22:24:46.777254+00	65	ae29f136-cd24-4d3b-a6c3-1aa03d5c812b	Adam	t	CONFIRMED	2	Time 2	2026-05-26 22:24:46.776969+00		\N	c7479212-3f63-4751-a39d-ca412b4194d0	\N	14.00	PENDING	\N
2026-06-02 20:59:35.591696+00	2026-06-02 20:59:35.591708+00	75	c7f32043-aa17-4582-a19f-fc23ae67bf1e	Daniel Gusmao	f	CONFIRMED	1	Time 1	2026-06-02 20:59:35.591411+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	7f11d3fd-7dc6-40ff-8362-8408d600cae7	0.00	WAIVED	\N
2026-06-02 20:35:07.415371+00	2026-06-02 20:35:07.415381+00	70	29b79f6a-d9d1-497a-aa1c-c02841242f29	Joao Pedro Marinho	f	CONFIRMED	2	Time 2	2026-06-02 20:35:07.415093+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	7726eb14-57d9-4835-bdbc-63b8605e4d5b	0.00	WAIVED	\N
2026-05-22 19:26:57.863024+00	2026-05-22 19:26:57.863034+00	68	a0d33e48-b0b0-4464-90b5-476f99c91e54	convidado 1	t	CONFIRMED	2	Time 2	2026-05-22 19:26:57.862806+00		\N	de6b38d3-6f48-42d3-80ad-7f8e0547abe3	\N	14.00	PENDING	\N
2026-05-22 19:37:24.41524+00	2026-05-22 19:37:24.415252+00	80	5fb4373d-e205-4196-bddf-f4c269958958	convidado 2	t	CONFIRMED	1	Time 1	2026-05-22 19:37:24.415018+00	qasdasadssad	\N	5f6aef1f-fcf5-4f90-bca7-0f082b8fdcb1	\N	14.00	PENDING	\N
2026-05-21 22:55:01.005164+00	2026-05-21 22:55:01.005176+00	68	852383e0-5224-4a8a-8148-ae792a7db394	Otoch	f	CONFIRMED	1	Time 1	2026-05-21 22:55:01.00486+00		\N	6a7665c5-dba3-423f-958e-ddd1ffb35962	0956ef3c-10d8-4ab4-8b9f-fe2ff7de8186	0.00	WAIVED	\N
2026-05-21 22:54:59.247787+00	2026-05-21 22:54:59.247799+00	67	87c6a3b4-4e83-4907-a126-58f351b5e393	Joao Pedro Marinho	f	CONFIRMED	2	Time 2	2026-05-21 22:54:59.247474+00		\N	6a7665c5-dba3-423f-958e-ddd1ffb35962	8a365ad9-5512-46c5-a8ac-793485b91fa9	0.00	WAIVED	\N
2026-05-22 19:26:47.613317+00	2026-05-22 19:26:47.613329+00	68	fb93a710-fc19-40dd-bbe7-4722dea34d95	Otoch	f	CONFIRMED	1	Time 1	2026-05-22 19:26:47.613061+00		\N	de6b38d3-6f48-42d3-80ad-7f8e0547abe3	0956ef3c-10d8-4ab4-8b9f-fe2ff7de8186	0.00	WAIVED	\N
2026-05-22 19:26:45.744582+00	2026-05-22 19:26:45.74461+00	66	27bf63c8-b995-44fa-a25e-678c7ef64515	Joao Pedro Marinho	f	CONFIRMED	3	Time 3	2026-05-22 19:26:45.74422+00		\N	de6b38d3-6f48-42d3-80ad-7f8e0547abe3	8a365ad9-5512-46c5-a8ac-793485b91fa9	0.00	WAIVED	\N
2026-05-22 19:37:09.126102+00	2026-05-22 19:37:09.126114+00	71	4221b33c-7ead-434e-8d00-bfee5225244b	Otoch	f	CONFIRMED	2	Time 2	2026-05-22 19:37:09.125815+00		\N	5f6aef1f-fcf5-4f90-bca7-0f082b8fdcb1	0956ef3c-10d8-4ab4-8b9f-fe2ff7de8186	0.00	WAIVED	\N
2026-05-22 19:37:07.625954+00	2026-05-22 19:37:07.625964+00	62	3fbccc3e-b482-4dca-a41c-b51db9312d2c	Joao Pedro Marinho	f	CONFIRMED	3	Time 3	2026-05-22 19:37:07.625699+00		\N	5f6aef1f-fcf5-4f90-bca7-0f082b8fdcb1	8a365ad9-5512-46c5-a8ac-793485b91fa9	0.00	WAIVED	\N
2026-06-02 20:58:56.337634+00	2026-06-02 20:58:56.337646+00	65	6bd3ead2-642b-4e3b-8960-27455875959e	Messias	f	CONFIRMED	2	Time 2	2026-06-02 20:58:56.337274+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	be21556d-bb4b-4543-81fe-6e5ad485e640	0.00	WAIVED	\N
2026-06-02 20:45:40.565087+00	2026-06-02 20:45:40.565099+00	52	0f5d9648-9847-41be-addb-5cf360f6485e	Delmaestro	f	CONFIRMED	2	Time 2	2026-06-02 20:45:40.56475+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	35ca46d3-d72b-4dde-ab0f-92e93516d974	0.00	WAIVED	\N
2026-06-02 20:37:44.533385+00	2026-06-02 20:37:44.533396+00	80	5f053524-3d26-491e-8b19-c019a0069705	Natan	f	CONFIRMED	3	Time 3	2026-06-02 20:37:44.533034+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	f128fd97-0889-4f74-bd90-de563d208df4	0.00	WAIVED	\N
2026-06-02 21:26:09.98101+00	2026-06-02 21:26:09.981022+00	70	215e85b5-0b2f-4f9b-b2a1-240772c9a4e2	Capadocia	f	CONFIRMED	3	Time 3	2026-06-02 21:26:09.980624+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	eae70bcb-fe53-4db3-b7c2-45302ec8f639	0.00	WAIVED	\N
2026-05-26 22:23:45.062881+00	2026-05-26 22:23:45.062898+00	90	a6366de8-36f3-4584-a218-1e158ede0c76	Luiz	f	CONFIRMED	1	Time 1	2026-05-26 22:23:45.06241+00		\N	c7479212-3f63-4751-a39d-ca412b4194d0	21c03d84-cf56-46ca-9f97-622dbda01b3b	0.00	WAIVED	\N
2026-05-26 22:23:40.414127+00	2026-05-26 22:23:40.414139+00	70	ec8878e4-c741-44bc-a884-e6b219feaf23	Hugo Otoch	f	CONFIRMED	1	Time 1	2026-05-26 22:23:40.413846+00		\N	c7479212-3f63-4751-a39d-ca412b4194d0	309428a4-2676-44e3-81e1-b9bc43f0b054	0.00	WAIVED	\N
2026-05-26 22:23:37.21854+00	2026-05-26 22:23:37.218552+00	70	488f6e88-841b-4f2e-9070-5873d25ef7bd	Eliezer	f	CONFIRMED	2	Time 2	2026-05-26 22:23:37.218221+00		\N	c7479212-3f63-4751-a39d-ca412b4194d0	2cbc86a1-f738-4a04-a1d9-231e50e78412	0.00	WAIVED	\N
2026-05-26 22:23:33.416885+00	2026-05-26 22:23:33.416898+00	60	f6dd5cbf-fe99-4a1e-8a60-9568be13bc23	Ailson	f	CONFIRMED	2	Time 2	2026-05-26 22:23:33.416381+00		\N	c7479212-3f63-4751-a39d-ca412b4194d0	488ef479-44a6-4a1a-9968-9c8bf81c87fa	0.00	WAIVED	\N
2026-05-26 22:24:20.253192+00	2026-05-26 22:24:20.253204+00	60	3d30e791-1742-4782-a198-cc39caa37b1d	Leozin	t	CONFIRMED	2	Time 2	2026-05-26 22:24:20.252929+00		\N	c7479212-3f63-4751-a39d-ca412b4194d0	\N	14.00	PENDING	\N
2026-05-26 22:23:48.638909+00	2026-05-26 22:23:48.63892+00	80	09946b7a-e948-48ff-aaaa-ab05ac160653	Natan	f	CONFIRMED	3	Time 3	2026-05-26 22:23:48.638636+00		\N	c7479212-3f63-4751-a39d-ca412b4194d0	f128fd97-0889-4f74-bd90-de563d208df4	0.00	WAIVED	\N
2026-05-26 22:23:38.244906+00	2026-05-26 22:23:38.244919+00	76	aa9ba60a-6c72-42bb-b038-fd2589b6b8d6	Gabriel Fraga	f	CONFIRMED	3	Time 3	2026-05-26 22:23:38.244595+00		\N	c7479212-3f63-4751-a39d-ca412b4194d0	8689491c-2717-45da-ad08-5c32336d071e	0.00	WAIVED	\N
2026-05-26 22:23:43.687408+00	2026-05-26 22:23:43.687419+00	70	cf91b304-d7ea-4955-87f2-c7e898955bc7	Julio	f	CONFIRMED	3	Time 3	2026-05-26 22:23:43.687138+00		\N	c7479212-3f63-4751-a39d-ca412b4194d0	a5bbfdb2-f3ac-4606-a81f-c687998a4c0e	0.00	WAIVED	\N
2026-05-26 22:23:49.744606+00	2026-05-26 22:23:49.744619+00	70	cfceed2c-5c51-46f7-8632-85a3dae01b7e	Renan	f	CONFIRMED	3	Time 3	2026-05-26 22:23:49.744329+00		\N	c7479212-3f63-4751-a39d-ca412b4194d0	1416232b-19fd-4b10-9f90-15f15610e72d	0.00	WAIVED	\N
2026-05-26 22:23:39.252888+00	2026-05-26 22:23:39.2529+00	60	30bc91e1-7052-4980-a28a-674a73abe013	Gabriel Holanda	f	CONFIRMED	3	Time 3	2026-05-26 22:23:39.2526+00		\N	c7479212-3f63-4751-a39d-ca412b4194d0	5f7a1fe7-9f47-4e73-bd99-435768c4fd6f	0.00	WAIVED	\N
2026-05-26 22:24:40.867367+00	2026-05-26 22:24:40.867378+00	55	651467b1-dfe9-4af1-b7b4-06c876723658	Patati	t	CONFIRMED	3	Time 3	2026-05-26 22:24:40.867127+00		\N	c7479212-3f63-4751-a39d-ca412b4194d0	\N	14.00	PENDING	\N
2026-06-02 20:45:39.421697+00	2026-06-02 20:45:39.421709+00	80	cbcc5d4a-839a-49c4-aa61-a3a9e2f495aa	Carlin	f	CONFIRMED	1	Time 1	2026-06-02 20:45:39.421424+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	330e5430-137a-420b-83b9-fa6e8d7a05e0	0.00	WAIVED	\N
2026-06-02 20:35:06.093456+00	2026-06-02 20:35:06.093467+00	70	e925bbdc-859a-414e-9085-f4d369e6f2cd	Hugo Otoch	f	CONFIRMED	2	Time 2	2026-06-02 20:35:06.093197+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	309428a4-2676-44e3-81e1-b9bc43f0b054	0.00	WAIVED	\N
2026-06-02 20:39:51.63856+00	2026-06-02 20:39:51.638572+00	55	dc4b8c09-506e-4fda-94df-6915950fde14	FP	t	CONFIRMED	2	Time 2	2026-06-02 20:39:51.638265+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	\N	14.00	PENDING	\N
2026-06-02 20:45:41.683699+00	2026-06-02 20:45:41.683711+00	65	3bf815d7-d331-4d5d-bc55-39c10fe808bc	Depiante	f	CONFIRMED	3	Time 3	2026-06-02 20:45:41.683381+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	45defeb7-ac1a-4431-a14b-50ee9a79570a	0.00	WAIVED	\N
2026-06-02 20:35:03.005754+00	2026-06-02 20:35:03.005764+00	60	1ffdfce4-7b40-4d98-b3d6-6da5d942e043	Gabriel Holanda	f	CONFIRMED	3	Time 3	2026-06-02 20:35:03.005508+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	5f7a1fe7-9f47-4e73-bd99-435768c4fd6f	0.00	WAIVED	\N
2026-06-02 20:47:27.171792+00	2026-06-02 20:47:27.171803+00	50	4ab1df65-a786-4c53-948c-33059f4fe950	PH	f	CONFIRMED	3	Time 3	2026-06-02 20:47:27.171539+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	c5572bc0-69f8-4a02-83bc-4d48907a5cb1	0.00	WAIVED	\N
2026-06-02 21:01:04.075363+00	2026-06-02 21:01:04.075377+00	72	0b3d5e57-4492-42ce-9359-268b3000697b	Gabriel Fraga	f	CONFIRMED	1	Time 1	2026-06-02 21:01:04.074983+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	8689491c-2717-45da-ad08-5c32336d071e	0.00	WAIVED	\N
2026-06-02 20:34:57.996344+00	2026-06-02 20:34:57.996356+00	65	c5d90fd3-fa8f-43bb-880a-0ad6cce8498c	Ailson	f	CONFIRMED	1	Time 1	2026-06-02 20:34:57.996022+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	488ef479-44a6-4a1a-9968-9c8bf81c87fa	0.00	WAIVED	\N
2026-06-02 20:38:14.903454+00	2026-06-02 20:38:14.903467+00	65	569a5398-c4ce-4481-add5-c0c0b5bb0334	Caioba	t	CONFIRMED	1	Time 1	2026-06-02 20:38:14.903146+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	\N	14.00	PENDING	\N
2026-06-02 20:37:51.336665+00	2026-06-02 20:37:51.336675+00	65	26ff3fa9-9740-45da-a52e-09ca7961bd2e	Thiago Mozzer	f	CONFIRMED	1	Time 1	2026-06-02 20:37:51.336398+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	651e725a-f346-4e13-9f4a-94074959a035	0.00	WAIVED	\N
2026-06-02 20:37:59.46673+00	2026-06-02 20:37:59.466742+00	40	24333a49-6842-4319-980c-5eee23367c4a	Rosinha	t	CONFIRMED	1	Time 1	2026-06-02 20:37:59.466485+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	\N	14.00	PENDING	\N
2026-06-02 20:47:52.419402+00	2026-06-02 20:47:52.419413+00	80	a9853764-ba99-4e58-837f-eeb3305ff85b	Luiz	f	CONFIRMED	2	Time 2	2026-06-02 20:47:52.419149+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	21c03d84-cf56-46ca-9f97-622dbda01b3b	0.00	WAIVED	\N
2026-06-02 20:37:47.961428+00	2026-06-02 20:37:47.961439+00	70	faae5e4e-5ef8-4fa2-bd29-c1ac71cbbc2d	Renan	f	CONFIRMED	2	Time 2	2026-06-02 20:37:47.961122+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	1416232b-19fd-4b10-9f90-15f15610e72d	0.00	WAIVED	\N
2026-06-02 20:35:04.566262+00	2026-06-02 20:35:04.566274+00	70	bccf136f-ce5e-468c-a8a1-35f76ad14299	Eliezer	f	CONFIRMED	3	Time 3	2026-06-02 20:35:04.565899+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	2cbc86a1-f738-4a04-a1d9-231e50e78412	0.00	WAIVED	\N
2026-06-02 20:35:08.839942+00	2026-06-02 20:35:08.839953+00	70	b2b19981-7cee-462d-a37b-f864ffb9b853	Julio	f	CONFIRMED	3	Time 3	2026-06-02 20:35:08.839655+00		\N	83a27a52-39d1-48c4-9b50-a5f8eabff78a	a5bbfdb2-f3ac-4606-a81f-c687998a4c0e	0.00	WAIVED	\N
\.


--
-- Data for Name: match_player_ratings; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.match_player_ratings (created_at, updated_at, id, score, match_id, rated_attendance_id, rated_player_id, rater_id, rater_user_id) FROM stdin;
2026-05-21 23:09:28.218876+00	2026-05-22 19:21:26.213399+00	1960b404-db66-4800-9b46-77313b9b6f9a	7	6a7665c5-dba3-423f-958e-ddd1ffb35962	87c6a3b4-4e83-4907-a126-58f351b5e393	8a365ad9-5512-46c5-a8ac-793485b91fa9	\N	3f7a79f3-158b-490a-aee6-79165c20047d
2026-05-21 23:09:28.22314+00	2026-05-22 19:21:26.217296+00	5452fc10-8fe5-446e-8204-80edb16d1881	7	6a7665c5-dba3-423f-958e-ddd1ffb35962	852383e0-5224-4a8a-8148-ae792a7db394	0956ef3c-10d8-4ab4-8b9f-fe2ff7de8186	\N	3f7a79f3-158b-490a-aee6-79165c20047d
2026-05-22 19:29:15.94936+00	2026-05-26 20:39:49.347673+00	200c8b20-1090-4bb7-982b-291a3c479727	1	de6b38d3-6f48-42d3-80ad-7f8e0547abe3	27bf63c8-b995-44fa-a25e-678c7ef64515	8a365ad9-5512-46c5-a8ac-793485b91fa9	\N	3f7a79f3-158b-490a-aee6-79165c20047d
2026-05-22 19:29:15.954637+00	2026-05-26 20:39:49.351262+00	4089ec39-093f-4c3d-a353-f02f8c7c5ce6	10	de6b38d3-6f48-42d3-80ad-7f8e0547abe3	fb93a710-fc19-40dd-bbe7-4722dea34d95	0956ef3c-10d8-4ab4-8b9f-fe2ff7de8186	\N	3f7a79f3-158b-490a-aee6-79165c20047d
2026-05-22 19:39:08.178857+00	2026-05-22 19:40:28.752764+00	dc82d4aa-e359-4fe1-b88e-b4c966ea4d6f	10	5f6aef1f-fcf5-4f90-bca7-0f082b8fdcb1	3fbccc3e-b482-4dca-a41c-b51db9312d2c	8a365ad9-5512-46c5-a8ac-793485b91fa9	\N	3f7a79f3-158b-490a-aee6-79165c20047d
2026-05-22 19:39:08.182453+00	2026-05-22 19:40:28.755593+00	3ddd6165-a546-4b40-afc7-f02dac34976d	1	5f6aef1f-fcf5-4f90-bca7-0f082b8fdcb1	4221b33c-7ead-434e-8d00-bfee5225244b	0956ef3c-10d8-4ab4-8b9f-fe2ff7de8186	\N	3f7a79f3-158b-490a-aee6-79165c20047d
\.


--
-- Data for Name: matches; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.matches (created_at, updated_at, id, scheduled_at, location, status, expected_team_count, attendance_locked_at, teams_generated_at, notes, created_by_id, result_recorded_at, result_summary, archived_at, ratings_finalized_at) FROM stdin;
2026-05-22 19:26:38.826556+00	2026-05-26 20:53:36.033415+00	de6b38d3-6f48-42d3-80ad-7f8e0547abe3	2026-05-24 23:00:00+00		ARCHIVED	3	2026-05-22 19:27:54.76853+00	2026-05-22 19:27:04.57719+00		bbd1d373-10e2-454c-bfac-4ecaebb5d40c	2026-05-22 19:27:28.925625+00	time a ganhou do time b de 5x0	\N	2026-05-26 20:53:36.033289+00
2026-05-22 19:36:50.916209+00	2026-05-26 20:53:36.046484+00	5f6aef1f-fcf5-4f90-bca7-0f082b8fdcb1	2026-05-23 00:00:00+00		ARCHIVED	3	2026-05-22 19:38:01.294648+00	2026-05-22 19:37:27.812246+00		bbd1d373-10e2-454c-bfac-4ecaebb5d40c	\N		\N	2026-05-26 20:53:36.046391+00
2026-05-21 19:32:38.225032+00	2026-05-26 20:53:36.057563+00	6a7665c5-dba3-423f-958e-ddd1ffb35962	2026-05-20 00:00:00+00	High society	ARCHIVED	3	2026-05-21 22:58:45.009639+00	2026-05-21 22:55:04.796375+00		bbd1d373-10e2-454c-bfac-4ecaebb5d40c	\N		\N	2026-05-26 20:53:36.057478+00
2026-04-14 14:33:41.447411+00	2026-05-26 20:53:36.06505+00	3c6bee81-445e-493a-9c2e-191aca2d244d	2026-04-15 00:00:00+00	high	ARCHIVED	3	2026-05-21 19:11:53.960051+00	\N		bbd1d373-10e2-454c-bfac-4ecaebb5d40c	\N		\N	2026-05-26 20:53:36.064993+00
2026-05-26 20:59:28.77918+00	2026-06-02 20:34:30.113763+00	c7479212-3f63-4751-a39d-ca412b4194d0	2026-05-27 00:00:00+00		ARCHIVED	3	2026-06-02 20:34:30.113549+00	2026-05-26 22:40:31.236756+00		bbd1d373-10e2-454c-bfac-4ecaebb5d40c	\N		2026-06-02 20:34:30.113541+00	\N
2026-06-02 20:34:42.192183+00	2026-06-02 21:26:42.992103+00	83a27a52-39d1-48c4-9b50-a5f8eabff78a	2026-06-03 00:00:00+00		OPEN	3	\N	2026-06-02 21:26:42.992014+00		bbd1d373-10e2-454c-bfac-4ecaebb5d40c	\N		\N	\N
\.


--
-- Data for Name: players; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.players (created_at, updated_at, overall, id, full_name, nickname, player_type, preferred_position, email, phone_number, shirt_number, monthly_fee_amount, joined_on, is_active, notes) FROM stdin;
2026-04-14 14:33:10.333515+00	2026-04-14 15:08:51.374553+00	65	65b004a4-42e4-4100-9588-d47202f045ea	Otoch		MEMBER	FORWARD			11	40.00	\N	f	
2026-05-21 22:36:30.355841+00	2026-05-21 22:54:49.095922+00	70	7b9a5761-3882-4e46-8b04-d565382500a5	teste		MEMBER	UNIVERSAL		27980000000	\N	0.00	\N	f	
2026-04-14 15:16:13.734171+00	2026-05-26 22:17:37.512762+00	63	8a365ad9-5512-46c5-a8ac-793485b91fa9	Joao Pedro Marinho	Marinho	MEMBER	MIDFIELDER			\N	40.00	\N	f	
2026-04-14 15:10:00.856953+00	2026-05-26 22:17:39.620631+00	63	0956ef3c-10d8-4ab4-8b9f-fe2ff7de8186	Otoch		MEMBER	FORWARD			11	40.00	\N	f	
2026-05-26 22:18:02.114803+00	2026-05-26 22:18:02.11482+00	70	309428a4-2676-44e3-81e1-b9bc43f0b054	Hugo Otoch	Otoch	MEMBER	FORWARD			11	40.00	\N	t	
2026-05-26 22:18:47.005909+00	2026-05-26 22:18:47.005923+00	70	a5bbfdb2-f3ac-4606-a81f-c687998a4c0e	Julio	Jotta	MEMBER	FORWARD			\N	40.00	\N	t	
2026-05-26 22:19:10.420057+00	2026-05-26 22:19:10.420071+00	65	651e725a-f346-4e13-9f4a-94074959a035	Thiago Mozzer	Mozzer	MEMBER	MIDFIELDER			\N	40.00	\N	t	
2026-05-26 22:19:23.054066+00	2026-05-26 22:19:23.054079+00	70	2cbc86a1-f738-4a04-a1d9-231e50e78412	Eliezer		MEMBER	FORWARD			\N	40.00	\N	t	
2026-05-26 22:19:39.643069+00	2026-05-26 22:19:39.643086+00	80	f128fd97-0889-4f74-bd90-de563d208df4	Natan		MEMBER	UNIVERSAL			\N	40.00	\N	t	
2026-05-26 22:21:06.016744+00	2026-05-26 22:21:06.016763+00	70	1416232b-19fd-4b10-9f90-15f15610e72d	Renan		MEMBER	DEFENDER			\N	40.00	\N	t	
2026-05-26 22:20:29.953255+00	2026-05-26 22:21:11.460983+00	70	7726eb14-57d9-4835-bdbc-63b8605e4d5b	Joao Pedro Marinho	Marinho	MEMBER	UNIVERSAL			\N	40.00	\N	t	
2026-05-26 22:21:41.625835+00	2026-05-26 22:21:41.625851+00	70	8ae512a8-21f8-4552-acb0-31935de4d194	Moises	Maridão	MEMBER	DEFENDER			\N	40.00	\N	t	
2026-05-26 22:22:44.520958+00	2026-05-26 22:22:44.520972+00	60	5f7a1fe7-9f47-4e73-bd99-435768c4fd6f	Gabriel Holanda	Holanda	MEMBER	MIDFIELDER			\N	40.00	\N	t	
2026-05-26 22:23:06.380698+00	2026-05-26 22:39:14.449416+00	45	5f39e8f8-8b69-470c-b557-64ec3ca76793	Baiano		MEMBER	FORWARD			\N	40.00	\N	t	
2026-05-26 22:20:44.806681+00	2026-05-26 23:13:27.790167+00	65	488ef479-44a6-4a1a-9968-9c8bf81c87fa	Ailson		MEMBER	DEFENDER			\N	40.00	\N	t	
2026-06-02 20:41:45.504722+00	2026-06-02 20:41:45.50474+00	52	35ca46d3-d72b-4dde-ab0f-92e93516d974	Delmaestro		MEMBER	MIDFIELDER			\N	40.00	\N	t	
2026-06-02 20:42:40.68612+00	2026-06-02 20:42:40.686133+00	65	45defeb7-ac1a-4431-a14b-50ee9a79570a	Depiante		MEMBER	MIDFIELDER			\N	40.00	\N	t	
2026-05-26 22:22:26.630974+00	2026-06-02 20:43:37.971557+00	80	21c03d84-cf56-46ca-9f97-622dbda01b3b	Luiz		MEMBER	UNIVERSAL			\N	40.00	\N	t	
2026-06-02 20:43:14.323481+00	2026-06-02 20:43:50.847509+00	80	330e5430-137a-420b-83b9-fa6e8d7a05e0	Carlin		MEMBER	UNIVERSAL			\N	40.00	\N	t	
2026-06-02 20:44:59.86947+00	2026-06-02 20:46:46.790382+00	50	c5572bc0-69f8-4a02-83bc-4d48907a5cb1	PH		MEMBER	FORWARD			\N	40.00	\N	t	
2026-05-26 22:20:20.393899+00	2026-06-02 20:50:59.097375+00	75	7f11d3fd-7dc6-40ff-8362-8408d600cae7	Daniel Gusmao	Gusmao	MEMBER	GOALKEEPER			\N	40.00	\N	t	
2026-05-26 22:22:14.408939+00	2026-06-02 20:58:15.504661+00	65	be21556d-bb4b-4543-81fe-6e5ad485e640	Messias		MEMBER	FORWARD			\N	40.00	\N	t	
2026-05-26 22:20:04.707806+00	2026-06-02 21:00:31.224137+00	72	8689491c-2717-45da-ad08-5c32336d071e	Gabriel Fraga	Fraga	MEMBER	UNIVERSAL			\N	40.00	\N	t	
2026-06-02 20:44:19.376603+00	2026-06-02 21:25:45.639372+00	70	eae70bcb-fe53-4db3-b7c2-45302ec8f639	Capadocia		MEMBER	DEFENDER			\N	40.00	\N	t	
\.


--
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.transactions (created_at, updated_at, id, direction, category, status, amount, description, occurred_on, reference_month, external_reference, notes, match_id, recorded_by_id, related_player_id) FROM stdin;
2026-04-14 14:35:09.284999+00	2026-04-14 14:35:09.285014+00	85443a94-5d75-4755-b4bb-8705bda02e78	INFLOW	MONTHLY_FEE	POSTED	40.00	Mensalidade Hugo Lima Otoch Demetrio de Souza - abril de 2026	2026-04-14	2026-04-01			\N	bbd1d373-10e2-454c-bfac-4ecaebb5d40c	65b004a4-42e4-4100-9588-d47202f045ea
2026-05-22 19:24:07.296791+00	2026-05-22 19:24:07.296806+00	ab193ef0-80ec-4486-bd18-5fea66c96dcd	INFLOW	MONTHLY_FEE	POSTED	40.00	Mensalidade Otoch - maio de 2026	2026-05-22	2026-05-01			\N	bbd1d373-10e2-454c-bfac-4ecaebb5d40c	0956ef3c-10d8-4ab4-8b9f-fe2ff7de8186
2026-05-22 19:34:37.637716+00	2026-05-22 19:34:37.63773+00	c47726a2-287f-4242-b05d-6d35a064fc4c	OUTFLOW	EQUIPMENT	POSTED	30.00	bola	2026-05-22	2026-05-01			\N	bbd1d373-10e2-454c-bfac-4ecaebb5d40c	\N
2026-05-22 19:35:18.775025+00	2026-05-22 19:35:18.775041+00	f94f0c20-aa5b-47da-a214-6c7a82e52f96	INFLOW	MONTHLY_FEE	POSTED	40.00	Mensalidade Joao Pedro Marinho - maio de 2026	2026-05-22	2026-05-01			\N	bbd1d373-10e2-454c-bfac-4ecaebb5d40c	8a365ad9-5512-46c5-a8ac-793485b91fa9
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (password, last_login, is_superuser, created_at, updated_at, username, first_name, last_name, email, is_staff, is_active, date_joined, id, role, display_name, must_change_password, linked_player_id, phone_number) FROM stdin;
pbkdf2_sha256$600000$mpcB3sca0vyqDYEuv8BhbF$05XBCj2wMCYy9i8AOnz1KoupVuMt0uHIF6057fLAozU=	\N	t	2026-04-14 14:10:58.849446+00	2026-05-21 19:28:45.362763+00	admsofredores			admsofredores@pelada.local	t	t	2026-04-14 14:10:58.849138+00	bbd1d373-10e2-454c-bfac-4ecaebb5d40c	ADMIN	Administrador Sofredores	f	\N	
pbkdf2_sha256$600000$VAy5JEvDxHMiDDiObpCgS7$4HYqwnv4aApe/QrUf7jUDTlJfs/98bpX5FY00K74IlI=	\N	f	2026-05-21 22:36:30.511953+00	2026-05-21 22:36:30.511961+00	teste				f	t	2026-05-21 22:36:30.363307+00	e0c910c5-a6c6-4ff0-a962-1c03209bb446	COMMON	teste	f	7b9a5761-3882-4e46-8b04-d565382500a5	27980000000
pbkdf2_sha256$600000$KbYqsXyuoNyFQ5auP14eZR$tUjZks542K62hKhkcGbthUsbv4tT2K5ua+OEuUnZbkg=	\N	f	2026-05-21 22:56:13.827487+00	2026-05-21 22:56:13.827494+00	teste2				f	t	2026-05-21 22:56:13.676831+00	3f7a79f3-158b-490a-aee6-79165c20047d	COMMON	teste2	f	\N	279809000000
\.


--
-- Data for Name: users_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 52, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 31, true);


--
-- Name: users_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_groups_id_seq', 1, false);


--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_user_permissions_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: match_attendances match_attendances_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_attendances
    ADD CONSTRAINT match_attendances_pkey PRIMARY KEY (id);


--
-- Name: match_player_ratings match_player_ratings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_player_ratings
    ADD CONSTRAINT match_player_ratings_pkey PRIMARY KEY (id);


--
-- Name: matches matches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_pkey PRIMARY KEY (id);


--
-- Name: players players_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: match_player_ratings unique_rating_per_user_attendance; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_player_ratings
    ADD CONSTRAINT unique_rating_per_user_attendance UNIQUE (match_id, rater_user_id, rated_attendance_id);


--
-- Name: users_groups users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_pkey PRIMARY KEY (id);


--
-- Name: users_groups users_groups_user_id_group_id_fc7788e8_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_group_id_fc7788e8_uniq UNIQUE (user_id, group_id);


--
-- Name: users users_linked_player_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_linked_player_id_key UNIQUE (linked_player_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_user_id_permission_id_3b86cbdf_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_permission_id_3b86cbdf_uniq UNIQUE (user_id, permission_id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: match_atten_attenda_904470_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX match_atten_attenda_904470_idx ON public.match_attendances USING btree (attendance_status);


--
-- Name: match_atten_is_gues_2de72c_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX match_atten_is_gues_2de72c_idx ON public.match_attendances USING btree (is_guest);


--
-- Name: match_attendances_invited_by_id_400424b5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX match_attendances_invited_by_id_400424b5 ON public.match_attendances USING btree (invited_by_id);


--
-- Name: match_attendances_match_id_89922346; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX match_attendances_match_id_89922346 ON public.match_attendances USING btree (match_id);


--
-- Name: match_attendances_player_id_cc43ea9d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX match_attendances_player_id_cc43ea9d ON public.match_attendances USING btree (player_id);


--
-- Name: match_playe_match_i_9812ca_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX match_playe_match_i_9812ca_idx ON public.match_player_ratings USING btree (match_id, rater_id);


--
-- Name: match_playe_match_i_b22529_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX match_playe_match_i_b22529_idx ON public.match_player_ratings USING btree (match_id, rater_user_id);


--
-- Name: match_playe_rated_p_c7e498_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX match_playe_rated_p_c7e498_idx ON public.match_player_ratings USING btree (rated_player_id);


--
-- Name: match_player_ratings_match_id_5c28f4d4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX match_player_ratings_match_id_5c28f4d4 ON public.match_player_ratings USING btree (match_id);


--
-- Name: match_player_ratings_rated_attendance_id_59ffd382; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX match_player_ratings_rated_attendance_id_59ffd382 ON public.match_player_ratings USING btree (rated_attendance_id);


--
-- Name: match_player_ratings_rated_player_id_376ab8c8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX match_player_ratings_rated_player_id_376ab8c8 ON public.match_player_ratings USING btree (rated_player_id);


--
-- Name: match_player_ratings_rater_id_7aa77871; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX match_player_ratings_rater_id_7aa77871 ON public.match_player_ratings USING btree (rater_id);


--
-- Name: match_player_ratings_rater_user_id_d99cc782; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX match_player_ratings_rater_user_id_d99cc782 ON public.match_player_ratings USING btree (rater_user_id);


--
-- Name: matches_created_by_id_c3b0b6b8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX matches_created_by_id_c3b0b6b8 ON public.matches USING btree (created_by_id);


--
-- Name: matches_schedul_821885_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX matches_schedul_821885_idx ON public.matches USING btree (scheduled_at);


--
-- Name: matches_status_639056_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX matches_status_639056_idx ON public.matches USING btree (status);


--
-- Name: players_full_na_5bfd7d_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX players_full_na_5bfd7d_idx ON public.players USING btree (full_name);


--
-- Name: players_is_acti_29de7e_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX players_is_acti_29de7e_idx ON public.players USING btree (is_active);


--
-- Name: players_player__efdeba_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX players_player__efdeba_idx ON public.players USING btree (player_type);


--
-- Name: transaction_categor_45fcdd_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transaction_categor_45fcdd_idx ON public.transactions USING btree (category);


--
-- Name: transaction_directi_d1d0f4_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transaction_directi_d1d0f4_idx ON public.transactions USING btree (direction, status);


--
-- Name: transaction_occurre_208c5b_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transaction_occurre_208c5b_idx ON public.transactions USING btree (occurred_on);


--
-- Name: transactions_match_id_be5e73dc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transactions_match_id_be5e73dc ON public.transactions USING btree (match_id);


--
-- Name: transactions_recorded_by_id_1ba20d63; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transactions_recorded_by_id_1ba20d63 ON public.transactions USING btree (recorded_by_id);


--
-- Name: transactions_related_player_id_d65540ca; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transactions_related_player_id_d65540ca ON public.transactions USING btree (related_player_id);


--
-- Name: unique_member_attendance_per_match; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX unique_member_attendance_per_match ON public.match_attendances USING btree (match_id, player_id) WHERE (player_id IS NOT NULL);


--
-- Name: users_groups_group_id_2f3517aa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_groups_group_id_2f3517aa ON public.users_groups USING btree (group_id);


--
-- Name: users_groups_user_id_f500bee5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_groups_user_id_f500bee5 ON public.users_groups USING btree (user_id);


--
-- Name: users_is_acti_847b48_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_is_acti_847b48_idx ON public.users USING btree (is_active);


--
-- Name: users_phone_n_a3b1c5_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_phone_n_a3b1c5_idx ON public.users USING btree (phone_number);


--
-- Name: users_role_0ace22_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_role_0ace22_idx ON public.users USING btree (role);


--
-- Name: users_user_permissions_permission_id_6d08dcd2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_permissions_permission_id_6d08dcd2 ON public.users_user_permissions USING btree (permission_id);


--
-- Name: users_user_permissions_user_id_92473840; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_permissions_user_id_92473840 ON public.users_user_permissions USING btree (user_id);


--
-- Name: users_username_e8658fc8_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_username_e8658fc8_like ON public.users USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: match_attendances match_attendances_invited_by_id_400424b5_fk_players_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_attendances
    ADD CONSTRAINT match_attendances_invited_by_id_400424b5_fk_players_id FOREIGN KEY (invited_by_id) REFERENCES public.players(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: match_attendances match_attendances_match_id_89922346_fk_matches_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_attendances
    ADD CONSTRAINT match_attendances_match_id_89922346_fk_matches_id FOREIGN KEY (match_id) REFERENCES public.matches(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: match_attendances match_attendances_player_id_cc43ea9d_fk_players_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_attendances
    ADD CONSTRAINT match_attendances_player_id_cc43ea9d_fk_players_id FOREIGN KEY (player_id) REFERENCES public.players(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: match_player_ratings match_player_ratings_match_id_5c28f4d4_fk_matches_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_player_ratings
    ADD CONSTRAINT match_player_ratings_match_id_5c28f4d4_fk_matches_id FOREIGN KEY (match_id) REFERENCES public.matches(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: match_player_ratings match_player_ratings_rated_attendance_id_59ffd382_fk_match_att; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_player_ratings
    ADD CONSTRAINT match_player_ratings_rated_attendance_id_59ffd382_fk_match_att FOREIGN KEY (rated_attendance_id) REFERENCES public.match_attendances(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: match_player_ratings match_player_ratings_rated_player_id_376ab8c8_fk_players_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_player_ratings
    ADD CONSTRAINT match_player_ratings_rated_player_id_376ab8c8_fk_players_id FOREIGN KEY (rated_player_id) REFERENCES public.players(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: match_player_ratings match_player_ratings_rater_id_7aa77871_fk_players_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_player_ratings
    ADD CONSTRAINT match_player_ratings_rater_id_7aa77871_fk_players_id FOREIGN KEY (rater_id) REFERENCES public.players(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: match_player_ratings match_player_ratings_rater_user_id_d99cc782_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.match_player_ratings
    ADD CONSTRAINT match_player_ratings_rater_user_id_d99cc782_fk_users_id FOREIGN KEY (rater_user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matches matches_created_by_id_c3b0b6b8_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_created_by_id_c3b0b6b8_fk_users_id FOREIGN KEY (created_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transactions transactions_match_id_be5e73dc_fk_matches_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_match_id_be5e73dc_fk_matches_id FOREIGN KEY (match_id) REFERENCES public.matches(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transactions transactions_recorded_by_id_1ba20d63_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_recorded_by_id_1ba20d63_fk_users_id FOREIGN KEY (recorded_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transactions transactions_related_player_id_d65540ca_fk_players_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_related_player_id_d65540ca_fk_players_id FOREIGN KEY (related_player_id) REFERENCES public.players(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_group_id_2f3517aa_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_group_id_2f3517aa_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_user_id_f500bee5_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_f500bee5_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users users_linked_player_id_6cf40e40_fk_players_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_linked_player_id_6cf40e40_fk_players_id FOREIGN KEY (linked_player_id) REFERENCES public.players(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissio_permission_id_6d08dcd2_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissio_permission_id_6d08dcd2_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissions_user_id_92473840_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_92473840_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 5jFZxnyv7Zg0kyQkGiutpL3rvWiTmDP3fXnPIY1pSMmht4FZehS2Vc5NreivRy8

