# Generated by Django 4.2.30 on 2026-04-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_match_result_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='match',
            new_name='matches_schedul_821885_idx',
            old_name='matches_scheduled_at_a21724_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='matches_status_639056_idx',
            old_name='matches_status_62959e_idx',
        ),
        migrations.RenameIndex(
            model_name='matchattendance',
            new_name='match_atten_attenda_904470_idx',
            old_name='attendance_status_029c7d_idx',
        ),
        migrations.RenameIndex(
            model_name='matchattendance',
            new_name='match_atten_is_gues_2de72c_idx',
            old_name='attendance_is_guest_18bafa_idx',
        ),
        migrations.RenameIndex(
            model_name='player',
            new_name='players_full_na_5bfd7d_idx',
            old_name='players_full_name_ee3668_idx',
        ),
        migrations.RenameIndex(
            model_name='player',
            new_name='players_player__efdeba_idx',
            old_name='players_player_type_6ec9c2_idx',
        ),
        migrations.RenameIndex(
            model_name='player',
            new_name='players_is_acti_29de7e_idx',
            old_name='players_is_active_0caad8_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_directi_d1d0f4_idx',
            old_name='transactions_direction_status_1bc8e5_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_categor_45fcdd_idx',
            old_name='transactions_category_440df5_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_occurre_208c5b_idx',
            old_name='transactions_occurred_on_435456_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_role_0ace22_idx',
            old_name='users_role_4f1c1e_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_is_acti_847b48_idx',
            old_name='users_is_active_0d2dc2_idx',
        ),
    ]
