# Generated by Django 4.2.30 on 2026-05-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_matches_scheduled_at_a21724_idx_matches_schedul_821885_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchattendance',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='matchattendance',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='matchattendance',
            name='dribble',
        ),
        migrations.RemoveField(
            model_name='matchattendance',
            name='goalkeeping',
        ),
        migrations.RemoveField(
            model_name='matchattendance',
            name='passing',
        ),
        migrations.RemoveField(
            model_name='matchattendance',
            name='shooting',
        ),
        migrations.RemoveField(
            model_name='matchattendance',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='matchattendance',
            name='stamina',
        ),
        migrations.RemoveField(
            model_name='matchattendance',
            name='tackle',
        ),
        migrations.RemoveField(
            model_name='player',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='player',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='player',
            name='dominant_foot',
        ),
        migrations.RemoveField(
            model_name='player',
            name='dribble',
        ),
        migrations.RemoveField(
            model_name='player',
            name='goalkeeping',
        ),
        migrations.RemoveField(
            model_name='player',
            name='passing',
        ),
        migrations.RemoveField(
            model_name='player',
            name='shooting',
        ),
        migrations.RemoveField(
            model_name='player',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='player',
            name='stamina',
        ),
        migrations.RemoveField(
            model_name='player',
            name='tackle',
        ),
    ]
