# Generated by Django 4.2.30 on 2026-05-21 21:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_matchattendance_attack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPlayerRating',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_ratings', to='core.match')),
                ('rated_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to='core.matchattendance')),
                ('rated_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_match_ratings', to='core.player')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_match_ratings', to='core.player')),
            ],
            options={
                'db_table': 'match_player_ratings',
                'ordering': ('match_id', 'rated_attendance__display_name'),
                'indexes': [models.Index(fields=['match', 'rater'], name='match_playe_match_i_9812ca_idx'), models.Index(fields=['rated_player'], name='match_playe_rated_p_c7e498_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='matchplayerrating',
            constraint=models.UniqueConstraint(fields=('match', 'rater', 'rated_attendance'), name='unique_rating_per_rater_attendance'),
        ),
        migrations.AddConstraint(
            model_name='matchplayerrating',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 1), ('score__lte', 10)), name='match_player_rating_score_1_10'),
        ),
    ]
