# Generated by Django 4.2.30 on 2026-08-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_match_two_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='rating_mode',
            field=models.CharField(choices=[('TEAM', 'Entre os proprios times'), ('GENERAL', 'Geral')], default='TEAM', max_length=16),
        ),
    ]
